# ---------- Builder ----------
FROM node:22-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY prisma ./prisma
RUN npx prisma generate

COPY . .
RUN npm prune --production


# ---------- Runtime ----------
FROM node:22-alpine

WORKDIR /app
COPY --from=builder /app ./

EXPOSE 3001
CMD ["npm", "start"]
