FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install --production

# Copy Prisma schema BEFORE generate
COPY prisma ./prisma

# Generate Prisma client
RUN npx prisma generate

# Copy the rest of the app
COPY . .

EXPOSE 3001

CMD ["npm", "start"]
